version: '3'

services:
  node:
    image: cardocker_node:nightly
    build: 
      context: ./node
      args:
        - RELEASE=master
    environment:
        - CONFIG=https://hydra.iohk.io/build/1545777/download/1/itn_rewards_v1-config.yaml
        - HASH=8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
        - ACCOUNT_ADDRESS
        - STORAGE_DIR
        - REST_PORT
        - PUBLIC_PORT
    ports:
      - "3000:3000"
      - "3100:3100"
    volumes:
      - ./storage/chain:/mnt/storage